#INFERNO reversal flagging pipeline

########commented block start########
#This code block renames MWT folder format (date and time of analysis) 
#with a more descriptive user generated format, inputted during MWT runs 
#(e.g. strain, treatment, time point, replicate number, date)
for i in `find ./* -maxdepth 1 -type d` 
  do 
   fld=$(basename $i/*.png .png)
   mv $i $fld
  done	                                
########commented block end########

########commented block start########
#This code block concatenates all .blobs files generated by MWT for each
#individual recording
for i in `find ./* -maxdepth 1 -type d` 
  do
    cat $i/*.blobs > $i.blobs
  done
########commented block end########

########commented block start########
#This code block creates a blobs folder and move all concatenated .blobs 
#files in the newly created blobs folder 
mkdir blobs
mv *.blobs blobs/
########commented block end########

########commented block start########
#This line runs the INFERNO_reversal_flagger_8fps.py python script
python2.7 /path/to/INFERNO_reversal_flagger_8fps.py
########commented block end########

########commented block start########
#This line moves concatenated .blobs used as input for the 
#INFERNO_reversal_flagger_8fps.py and the .txt 
#INFERNO_reversal_flagger_8fps.py output files containing 
#reversal data from the blobs folder to the output folder 
mv blobs output 
########commented block end########